### ISSUE TITLE
Remove alertmangers stored state from Prometheus Charm

### ISSUE THREAD

**Issue by balbirthomas** [canonical/alertmanager-operator#10]
## Overview

A recent commit to Alertmanager created a charm library for managing relations between Prometheus and Alertmanager. This library uses stored state to store the list of Alertmanagers that Prometheus must forward alerts to. However the older design used a stored state within the Prometheus Charm to store this list of Alertmanagers. Hence there are now two locations where this list is stored. Even though this is a change that must be done in the Prometheus respository, it is a change that must happen in conjunction with switching Alertmanager to the Alertmanager library, hence this issue is being reported here.

**Comment by sed-i** [comment]
Fixed in #13 and https://github.com/canonical/prometheus-operator/pull/48
